// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8zGC9KMdnk2m4xerm9bz5MGgdM2AoKU0',
    appId: '1:338003119154:web:c3a951a2b4f74a15d2002b',
    messagingSenderId: '338003119154',
    projectId: 'ecomerce-fb',
    authDomain: 'ecomerce-fb.firebaseapp.com',
    storageBucket: 'ecomerce-fb.firebasestorage.app',
    measurementId: 'G-PKZM8L95R4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAamCrdqalwsPDOCnszmlTal4tppUbK86I',
    appId: '1:338003119154:android:9cb404efce169997d2002b',
    messagingSenderId: '338003119154',
    projectId: 'ecomerce-fb',
    storageBucket: 'ecomerce-fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdwWIjud1O1orrEJEii6cJ7vQDskSum5U',
    appId: '1:338003119154:ios:ffa40b5f744914eed2002b',
    messagingSenderId: '338003119154',
    projectId: 'ecomerce-fb',
    storageBucket: 'ecomerce-fb.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdwWIjud1O1orrEJEii6cJ7vQDskSum5U',
    appId: '1:338003119154:ios:ffa40b5f744914eed2002b',
    messagingSenderId: '338003119154',
    projectId: 'ecomerce-fb',
    storageBucket: 'ecomerce-fb.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8zGC9KMdnk2m4xerm9bz5MGgdM2AoKU0',
    appId: '1:338003119154:web:3e3a411c7c8cd4c4d2002b',
    messagingSenderId: '338003119154',
    projectId: 'ecomerce-fb',
    authDomain: 'ecomerce-fb.firebaseapp.com',
    storageBucket: 'ecomerce-fb.firebasestorage.app',
    measurementId: 'G-8H95XZHT1P',
  );
}
